# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  TESTVARIABLE: $(testvariable)
  GITHUB_TOKEN: $(githubtoken)

steps:
- script: |
    curl -sSL "https://raw.githubusercontent.com/wayner-ferreira/web-app-testes/main/index.html" -o index.html
    sed -i "2s|.*|<html><head><title>Título</title></head><body><h1>$(testvariable)</h1></body></html>|" index.html
    curl -u $(GITHUB_TOKEN):x-oauth-basic -X PUT -d @index.html "https://api.github.com/repos/seu-usuario/seu-repositorio/contents/index.html"
  displayName: 'Atualizar Valor em index.html'
  env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.'
    ArtifactName: 'drop'
    publishLocation: 'Container'