trigger:
- main

pr:
- '*'

steps:
- task: DockerCompose@0
  displayName: 'Execute Docker Compose up'
  inputs:
    containerregistrytype: 'Azure Container Registry'
    azureSubscription: 'Azure for Students(b644be36-9223-42a4-8a5d-a326f8e0af33)'
    azureContainerRegistry: '{"loginServer":"acrwayner.azurecr.io", "id" : "/subscriptions/b644be36-9223-42a4-8a5d-a326f8e0af33/resourceGroups/rg-testes-wayner/providers/Microsoft.ContainerRegistry/registries/acrwayner"}'
    dockerComposeFile: '**/docker-compose.yml'
    action: 'Run a Docker Compose command'
    dockerComposeCommand: 'up'