# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
  
variables:
  TESTVARIABLE: $(testvariable)
  GITHUB_TOKEN: $(githubtoken)

steps:
- script: |
    curl -sSL "https://raw.githubusercontent.com/waynerferreira/web-app-testes/main/index.html" -o index.html
    sed -i "2s|.*|<html><head><title>Título</title></head><body><h1>$(TESTVARIABLE)</h1></body></html>|" index.html
    curl -u $(GITHUB_TOKEN):x-oauth-basic -X PUT -d @index.html "https://api.github.com/repos/waynerferreira/web-app-testes/contents/index.html"
  displayName: 'Atualizar Valor em index.html'
  env:
    GITHUB_TOKEN: $(GITHUB_TOKEN)

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '.'
    ArtifactName: 'drop'
    publishLocation: 'Container'